### ISSUE TITLE
Change alert keys

### ISSUE THREAD

**Issue by flound1129** [bitcoinclassic/website#4]
Alert keys should be changed before release.

**Comment by jtoomim** [comment]
Is this for the website, or for the actual Bitcoin Classic code? I think you might be opening this issue in the wrong repo.

**Comment by flound1129** [comment]
code.. oops.

**Comment by flound1129** [comment]
does the code have issues enabled?  doesn't seem so.

**Comment by ahmedbodi** [comment]
@flound1129 nice catch, enabled issues on the code git
