### ISSUE TITLE
Limit sigops in a block

### ISSUE THREAD

**Issue by judahmu** [bitcoinclassic/website#6]
The problem is basically described in the Motivation section of [BIP 143](https://github.com/bitcoin/bips/blob/master/bip-0143.mediawiki#Motivation).

It would be efficient and maintainable to springboard off the code in support of [BIP 143](https://github.com/bitcoin/bips/blob/master/bip-0143.mediawiki) if available and usable without much change.  

Another candidate is a patch from from XT: [Implement accurate sigop / sighashbytes counting block consensus rules](https://github.com/bitcoinxt/bitcoinxt/commit/cc1a7b53629b265e1be6e212d64524f709d27022)

We do not know the future use cases of Bitcoin or future technological advancements, will changes to how complicated a block may get require a future hard fork?

**Comment by jtoomim** [comment]
This does not appear to be a website issue.

Note that https://github.com/bitcoinclassic/bitcoinclassic/pull/3 already includes code for this.

**Comment by judahmu** [comment]
This isn't Version Bits. It is to limit more of those 1 MB sized transactions.  

agreed, this is certainly not a website issue.

**Comment by jtoomim** [comment]
> It is to limit more of those 1 MB sized transactions.

Which PR 3 already has, as I mentioned.

**Comment by maduhu** [comment]
@judahmu "Need help Please brother" - I am JAVA Developer from Africa(Tanzania), I am struggling in making Cyclos 3 SMS Module work with My installation but have No success, Would you be kind enough to help me with Instruction how to solve this !!! I Do not have money to pay you now, but I can always make you a WordPress website to repay you if you help me!

Please and Please brother, Help me we this, Contact me via my mail : maduhu1988 (at) yahoo (dot) co (dot) uk

Kindly find the attached configuration Documents of my SMS module installation to see what I have done and Advice me If possible.

Thank you in Advance! 
Paschal Maduhu,
JAVA Developer, Tanzania - Africa
http://africa.cloudapp.net/maduhu

[configuration-files.zip](https://github.com/bitcoinclassic/website/files/149634/configuration-files.zip)
